# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db import *
def suppress_qt_warnings():
    environ["QT_DEVICE_PIXEL_RATIO"] = "0"
    environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    environ["QT_SCREEN_SCALE_FACTORS"] = "1"
    environ["QT_SCALE_FACTOR"] = "1"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #5D6D7E;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Heading = QtWidgets.QLabel(self.centralwidget)
        self.Heading.setGeometry(QtCore.QRect(210, 0, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Heading.setFont(font)
        self.Heading.setStyleSheet("text-decoration: underline")
        self.Heading.setObjectName("Heading")
        self.btn_register = QtWidgets.QPushButton(self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(20, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register.setFont(font)
        self.btn_register.setObjectName("btn_register")
        self.btn_register.clicked.connect(self.visible_register)
        self.btn_register.setCheckable(False)

        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(10, 220, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.btn_login.clicked.connect(self.visible_login)
        self.btn_login.setCheckable(False)

        self.RegisterForm = QtWidgets.QGroupBox(self.centralwidget)
        self.RegisterForm.setEnabled(True)
        self.RegisterForm.setGeometry(QtCore.QRect(110, 50, 451, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RegisterForm.setFont(font)
        self.RegisterForm.setObjectName("RegisterForm")
        self.RegisterForm.setVisible(False)

        # Oblect's Register Form
        self.pushButton = QtWidgets.QPushButton(self.RegisterForm)
        self.pushButton.setGeometry(QtCore.QRect(330, 40, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.receiving_parameters)
        self.lineEdit = QtWidgets.QLineEdit(self.RegisterForm)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.RegisterForm)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 50, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.RegisterForm)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 80, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.RegisterForm)
        self.label.setGeometry(QtCore.QRect(30, 30, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.RegisterForm)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.RegisterForm)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 91, 16))
        self.label_3.setObjectName("label_3")

        self.LoginForm = QtWidgets.QGroupBox(self.centralwidget)
        self.LoginForm.setGeometry(QtCore.QRect(110, 170, 451, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LoginForm.setFont(font)
        self.LoginForm.setObjectName("LoginForm")
        self.LoginForm.setVisible(False)

        self.pushButton_3 = QtWidgets.QPushButton(self.LoginForm)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 40, 81, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.LoginForm)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 30, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.LoginForm)
        self.lineEdit_5.setGeometry(QtCore.QRect(170, 60, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_4 = QtWidgets.QLabel(self.LoginForm)
        self.label_4.setGeometry(QtCore.QRect(40, 40, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.LoginForm)
        self.label_5.setGeometry(QtCore.QRect(40, 60, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 310, 111, 261))
        self.label_6.setObjectName("label_6")
        self.btn_vote = QtWidgets.QPushButton(self.centralwidget)
        self.btn_vote.setGeometry(QtCore.QRect(600, 540, 75, 23))
        self.btn_vote.setObjectName("btn_vote")
        self.input_candidate = QtWidgets.QLineEdit(self.centralwidget)
        self.input_candidate.setGeometry(QtCore.QRect(552, 510, 191, 20))
        self.input_candidate.setObjectName("input_candidate")
        self.candidates_list = QtWidgets.QLabel(self.centralwidget)
        self.candidates_list.setGeometry(QtCore.QRect(520, 330, 231, 161))
        self.candidates_list.setAlignment(QtCore.Qt.AlignCenter)
        self.candidates_list.setObjectName("candidates_list")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Heading.setText(_translate("MainWindow", "Welcome to System Voice!"))
        self.btn_register.setText(_translate("MainWindow", "Register"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.RegisterForm.setTitle(_translate("MainWindow", "Register Form"))
        self.pushButton.setText(_translate("MainWindow", "Create account"))
        self.label.setText(_translate("MainWindow", "Enter username"))
        self.label_2.setText(_translate("MainWindow", "Enter login"))
        self.label_3.setText(_translate("MainWindow", "Enter passwd"))
        self.LoginForm.setTitle(_translate("MainWindow", "Login Form"))
        self.pushButton_3.setText(_translate("MainWindow", "Login"))
        self.label_4.setText(_translate("MainWindow", "Enter your  login"))
        self.label_5.setText(_translate("MainWindow", "Enter your password"))
        self.label_6.setText(_translate("MainWindow", "Results"))
        self.btn_vote.setText(_translate("MainWindow", "Vote"))
        self.candidates_list.setText(_translate("MainWindow", "Candidates list"))


    def visible_login(self):
        if self.btn_login.isChecked() == False:
            self.LoginForm.setVisible(True)
            self.btn_login.setCheckable(True)
        else:
            self.LoginForm.setVisible(False)

    def visible_register(self):
        if self.btn_register.isChecked() == False:
            self.RegisterForm.setVisible(True)
            self.btn_register.setCheckable(True)
        else:
            self.RegisterForm.setVisible(False)

    def receiving_parameters(self):
        # self.label_6
        pass

if __name__ == "__main__":
    import sys
    from os import environ
    suppress_qt_warnings()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
